"""Unified safety guardrail combining all three layers."""

from dataclasses import dataclass
from enum import Enum

from loguru import logger

from app.safety.rule_engine import RuleEngine
from app.safety.classifier import PromptClassifier


class BlockReason(str, Enum):
    INJECTION_RULE = "injection_rule"
    INJECTION_CLASSIFIER = "injection_classifier"
    DANGEROUS_COMMAND = "dangerous_command"
    HIGH_RISK_INTENT = "high_risk_intent"


@dataclass
class SafetyCheckResult:
    """Combined result from all safety layers."""
    is_safe: bool
    blocked_by: BlockReason | None = None
    detail: str | None = None
    layers_checked: list[str] = None
    is_warning: bool = False  # True = not blocked, but flagged as risky

    def __post_init__(self):
        if self.layers_checked is None:
            self.layers_checked = []


class SafetyGuardrail:
    """
    Three-layer safety guardrail.

    Layer 1: Rule engine (regex/keyword) - fast, catches obvious attacks
    Layer 2: BERT classifier - semantic detection, independent of main LLM
    Layer 3: LLM system prompt - always active, last line of defense

    Layer 3 is not checked here (it's embedded in the LLM call).
    This class handles Layer 1 and Layer 2.
    """

    def __init__(self):
        self._rule_engine = RuleEngine()
        self._classifier = PromptClassifier()

    @property
    def security_mode(self) -> str:
        """Current security mode description."""
        if self._classifier.is_available:
            return "full (3-layer)"
        return "degraded (2-layer: rules + LLM constraints)"

    def check_input(self, text: str) -> SafetyCheckResult:
        """
        Check user input through Layer 1 and Layer 2.

        Returns immediately on first block.
        """
        layers_checked = []

        # Layer 1: Rule engine
        rule_result = self._rule_engine.check_input(text)
        layers_checked.append("rule_engine")

        if not rule_result.is_safe:
            logger.warning(f"Input blocked by rule engine: {rule_result.matched_rule}")
            return SafetyCheckResult(
                is_safe=False,
                blocked_by=BlockReason.INJECTION_RULE,
                detail=f"匹配到注入模式: {rule_result.matched_rule}",
                layers_checked=layers_checked,
            )

        # Layer 2: BERT classifier (if available)
        if self._classifier.is_available:
            classifier_result = self._classifier.classify(text)
            layers_checked.append("classifier")

            if not classifier_result.is_safe:
                logger.warning(
                    f"Input blocked by classifier (confidence: {classifier_result.confidence:.2f})"
                )
                return SafetyCheckResult(
                    is_safe=False,
                    blocked_by=BlockReason.INJECTION_CLASSIFIER,
                    detail=f"语义分析检测到注入攻击 (置信度: {classifier_result.confidence:.1%})",
                    layers_checked=layers_checked,
                )

        # All checks passed
        return SafetyCheckResult(is_safe=True, layers_checked=layers_checked)

    def check_high_risk_intent(self, text: str) -> SafetyCheckResult:
        """Check if input contains high-risk intent (warning, not block).

        Returns a warning result that the Agent should use to be extra cautious.
        """
        intent_result = self._rule_engine.check_high_risk_intent(text)
        if not intent_result.is_safe:
            return SafetyCheckResult(
                is_safe=True,  # Not blocked, just warned
                is_warning=True,
                blocked_by=BlockReason.HIGH_RISK_INTENT,
                detail=f"检测到高风险意图: {intent_result.matched_rule}",
                layers_checked=["intent_check"],
            )
        return SafetyCheckResult(is_safe=True, layers_checked=["intent_check"])

    def check_command(self, command: str) -> SafetyCheckResult:
        """Check a command generated by the LLM before execution."""
        rule_result = self._rule_engine.check_command(command)

        if not rule_result.is_safe:
            logger.warning(f"Command blocked: {command}")
            return SafetyCheckResult(
                is_safe=False,
                blocked_by=BlockReason.DANGEROUS_COMMAND,
                detail=f"检测到危险命令模式: {rule_result.matched_rule}",
                layers_checked=["rule_engine"],
            )

        return SafetyCheckResult(is_safe=True, layers_checked=["rule_engine"])
